# Generated by Django 3.2.7 on 2021-12-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211201_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Address',
            field=models.CharField(default=12, max_length=50, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='person',
            name='DOB',
            field=models.CharField(default=12, max_length=12, verbose_name='dob'),
        ),
        migrations.AddField(
            model_name='person',
            name='FirstName',
            field=models.CharField(default=12, max_length=50, verbose_name='FirstName'),
        ),
        migrations.AddField(
            model_name='person',
            name='Gender',
            field=models.CharField(max_length=12, null='True', verbose_name='gender'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='person',
            name='LastName',
            field=models.CharField(default=12, max_length=50, verbose_name='LastName'),
        ),
        migrations.AddField(
            model_name='person',
            name='contact',
            field=models.IntegerField(default=12, max_length=19, verbose_name='contact'),
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default=12, max_length=80, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='person',
            name='repassword',
            field=models.CharField(default=12, max_length=8, verbose_name='repassword'),
        ),
    ]
